export const phrases = [
  "No",
  "Are you sure?",
  "Really sure?",
  "Pleaseeee",
  "I'm begging you",
  "You're making a mistake...",
  "You're breaking my heart ;(",
  "Pause before 'no'; say 'yes' to being my valentine.",
  "Imagine joy as valentines before rejecting.",
  "Think twice; being mine could be fun.",
  "Ponder my valentine possibility before 'no'.",
  "Hold off on 'no'; picture shared smiles.",
  "Envision happiness; be my valentines.",
  "Reconsider; surprise awaits as my valentine.",
  "Think warmth before denying.",
  "Pause; imagine valentine excitement.",
  "Imagine romance before swift 'no'.",
  "Share love; don't dismiss.",
  "Think magic together before deciding.",
  "Picture shared laughter before 'no'.",
  "Ponder valentine potential before rejecting.",
  "Feel joy as my valentines.",
  "Hold off; adventure awaits as my valentine.",
  "Consider possibility before declining.",
  "Pause; brighten my day as my valentine.",
  "Create memories; don't say 'no'.",
  "Hold back; imagine valentine happiness."
]